import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Provider from "./all-collection/Provider";
import ContextProvider from "./ContextApi/ContextProvider";
import Navbar from "./Component/Navbar";
import Footer from "./Component/Footer";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Foodify web",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Provider>
        <ContextProvider>
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            <Navbar />
            {children}
            <Footer />
          </body>
        </ContextProvider>
      </Provider>
    </html>
  );
}