import { Geist } from "next/font/google";
import "./globals.css";

import Navbar from "./Component/Navbar";
import ContextProvider from "./ContextApi/ContextProvider";
import Footer from "./Component/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Next Js Project",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
   

        <ContextProvider>
        <body className={`${geistSans.variable} antialiased`}>
          <div className='h-[80px]'>
            <Navbar />
          </div>
          {children}
          <Footer />
        </body>
        </ContextProvider>
 
    
    </html>
  );
}
